FixTime = false
Title = "assetchain-test"
ChainID=10001
version="1.0.0"
CoinSymbol="OCIA"
CoinPrecision=10000

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
logConsoleLevel = "info"
loglevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/assetchain.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = true
# 是否打印调用方法
callerFunction = false

[blockchain]
batchsync = false
defCacheSize=512
dbCache = 512
dbPath = "/data/assetchaindatadir"
enableTxQuickIndex = true
isRecordBlockSequence = true
# 升级storedb是否重新执行localdb，主链升级不需要开启，平行链升级需要开启
enableReExecLocal = false
# 使能精简localdb
enableReduceLocaldb = false
enablePushSubscribe = true
singleMode = false
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
isStrongConsistency=false
disableShard=true
onChainTimeout=1

[mempool]
poolCacheSize=102400
#minTxFeeRate=0
minTxFeeRate=10
maxTxFeeRate=1000
disableExecCheck=true
maxTxNumPerAccount = 30000
name="price"
maxTxFee=100000
isLevelFee=true

[mempool.sub.score]
poolCacheSize=102400
minTxFee=10
maxTxNumPerAccount=30000
timeParam=1      #时间占价格比例
priceConstant=1544  #手续费相对于时间的一个合适的常量,取当前unxi时间戳前四位数,排序时手续费高1e-5~=快1s
pricePower=1     #常量比例

[mempool.sub.price]
poolCacheSize=102400

[p2p]
enable=true
dbCache = 4
driver="leveldb"
dbPath = "/data/assetchaindatadir/addrbook"
grpcLogFile = "grpc33.log"
types = ["dht"]
#waitPid 等待seed导入
waitPid = false

[p2p.sub.gossip]
innerBounds = 300
innerSeedEnable = false
isSeed = false
port = 13802
seeds = []
useGithub = false
msgCacheSize=10240
serverStart=true

[p2p.sub.dht]
#可以自定义设置连接节点
channel = 10001
port = 13801

seeds = ["/ip4/218.75.123.183/tcp/13801/p2p/16Uiu2HAkzFQ5BVEQKXPbMqga6wkmtb1Rh2bH5sXaWtVyuR5GeLxv"]
# seeds = ["/ip4/10.89.3.10/tcp/13801/p2p/16Uiu2HAkzFQ5BVEQKXPbMqga6wkmtb1Rh2bH5sXaWtVyuR5GeLxv"]

#限定连接数
#暂时限定较小的连接数
maxConnectNum = 50
#区块轻广播最低区块大小，1k
minLtBlockSize = 1
# 是否配置为全节点模式，全节点保存所有分片数据，种子节点应配置为true
isFullNode = true
#设为1为屏蔽默认设置5
maxBroadcastPeers = 1

[p2p.sub.dht.pubsub]
gossipSubD = 10
gossipSubDhi = 20
gossipSubDlo = 7
gossipSubHeartbeatInterval = 900
gossipSubHistoryGossip = 2
gossipSubHistoryLength = 7


[rpc]
certFile = "cert.pem"
enableTLS = false
grpcBindAddr = "localhost:8802"
grpcFuncWhitelist = ["*"]
jrpcBindAddr = "localhost:8801"
jrpcFuncWhitelist = ["*"]
keyFile = "key.pem"
whitelist = ["127.0.0.1"]

[consensus]
name="pos33"
minerstart=true
genesisBlockTime=1604449783
genesis="163eimvjqQacXh6evrmRpRxXRCxKqHUT88"
minerExecs=["pos33"]

[consensus.sub.pos33]
bootPeers = ["/ip4/218.75.123.183/tcp/10901/p2p/16Uiu2HAmVqWHXxNwPsYCA1nV5CUgGxBEBwhsX5gu1ERx8sbPmM52"]
#bootPeers = ["/ip4/10.89.3.10/tcp/10901/p2p/16Uiu2HAmVqWHXxNwPsYCA1nV5CUgGxBEBwhsX5gu1ERx8sbPmM52"]
forwardServers = [] 
listenPort = 10901
onlyVoter = false
genesisBlockTime=1611627559
checkFutureBlockHeight=1500000

[[consensus.sub.pos33.genesis]]
minerAddr="19AqkFqEEB4kRxfnYomuAx4TgxeHw53X99"
returnAddr="163eimvjqQacXh6evrmRpRxXRCxKqHUT88"
count=10000

[mver.consensus]
fundKeyAddr="14wDnMse45jomBWx1AuHB6KDhVz662YJMx"
powLimitBits="0x1f00ffff"
maxTxNumber=30000

[mver.consensus.ForkChainParamV1]
maxTxNumber=30000

[mver.consensus.ForkChainParamV2]
powLimitBits="0x1f2fffff"

[mver.consensus.ForkTicketFundAddrV1]
fundKeyAddr="14wDnMse45jomBWx1AuHB6KDhVz662YJMx"

[mver.consensus.pos33]
coinReward=18
coinDevFund=12
ticketPrice=10000
retargetAdjustmentFactor=4
futureBlockTime=5
ticketFrozenTime=43200
ticketWithdrawTime=10
ticketMinerWaitTime=7200
targetTimespan=2160
targetTimePerBlock=15

[store]
dbCache = 512
dbPath = "/data/assetchaindatadir/mavltree"
name="kvmvccmavl"
driver="leveldb"
storedbVersion="2.0.0"

[store.sub.mavl]
enableMVCC = false
enableMavlPrefix = true
enableMavlPrune = true
enableMemTree = true
enableMemVal = true
pruneHeight = 10000
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen = 200000

[store.sub.kvmvccmavl]
enableMVCC = false
enableMVCCIter = true
enableMVCCPrune = false
enableMavlPrefix = true
enableMavlPrune = true
enableMemTree = true
enableMemVal = true
pruneMVCCHeight = 10000
pruneMavlHeight = 10000
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen = 200000

[crypto]
enableTypes = ["secp256k1", "none", "bls"]

[wallet]
dbCache = 16
dbPath = "/data/assetchainwallet"
minFee=10
driver="leveldb"
signType="secp256k1"

[fork.system]
ForkChainParamV1=0
ForkCheckTxDup=0
# TODO 正式链配置为 1
ForkBlockHash=1
ForkMinerTime=0
ForkTransferExec=0
ForkExecKey=0
ForkTxGroup=0
ForkResetTx0=0
ForkWithdraw=0
ForkExecRollback=0
ForkCheckBlockTime=0
ForkTxHeight=0
ForkTxGroupPara=0
ForkChainParamV2=0
ForkMultiSignAddress=0
ForkStateDBSet=0
ForkLocalDBAccess=0
ForkBlockCheck=0
ForkBase58AddressCheck=0
#平行链上使能平行链执行器如user.p.x.coins执行器的注册，缺省为0，对已有的平行链需要设置一个fork高度
ForkEnableParaRegExec=0
ForkCacheDriver=0
ForkTicketFundAddrV1=-1 #fork6.3
#主链和平行链都使用同一个fork高度
ForkRootHash=0 

[fork.sub.coins]
Enable=0

[fork.sub.pos33]
Enable=0

[fork.sub.ticket]
Enable=0
ForkTicketId = 0 
ForkTicketVrf = 0

[fork.sub.retrieve]
Enable=0
ForkRetrive=0
ForkRetriveAsset=0

[fork.sub.hashlock]
Enable=0
ForkBadRepeatSecret=0

[fork.sub.manage]
Enable=0
ForkManageExec=0

[fork.sub.token]
Enable=0
ForkTokenBlackList=0
ForkBadTokenSymbol=0
ForkTokenPrice=300000
ForkTokenSymbolWithNumber=0
ForkTokenCheck=0

[fork.sub.trade]
Enable=0
ForkTradeBuyLimit=0
ForkTradeAsset=0
ForkTradeID=0
ForkTradeFixAssetDB=0
ForkTradePrice=0


[fork.sub.paracross]
Enable=0
ForkParacrossWithdrawFromParachain=0
ForkParacrossCommitTx=0
ForkLoopCheckCommitTxDone=0
#fork for 6.4
ForkParaAssetTransferRbk=0
ForkParaSelfConsStages=0
#仅平行链适用
ForkParaFullMinerHeight=-1
ForkParaRootHash=0
ForkParaSupervision=0

[fork.sub.multisig]
Enable=0

[fork.sub.autonomy]
Enable=0
ForkAutonomyDelRule=0

[fork.sub.unfreeze]
Enable=0
ForkTerminatePart=0
ForkUnfreezeIDX=0

[fork.sub.store-kvmvccmavl]
ForkKvmvccmavl=0

[fork.sub.evm]
Enable=0
ForkEVMState=0
ForkEVMABI=0
ForkEVMFrozen=0
ForkEVMKVHash=0
ForkEVMYoloV1=0
ForkEVMTxGroup=0


[exec]
enableMVCC = false
enableStat = false
#disableAddrIndex=true

[exec.sub.pos33]
ForkTicketId=0
ForkTicketVrf=0

[exec.sub.token]
#配置一个空值，防止配置文件被覆盖
tokenApprs=["13jXcaJB3Sg7oBB2FAZf3VbDB58gHn7PPd"]
saveTokenTxList = false

[exec.sub.relay]
genesis="13jXcaJB3Sg7oBB2FAZf3VbDB58gHn7PPd"

[exec.sub.manage]
superManager=[
    "13jXcaJB3Sg7oBB2FAZf3VbDB58gHn7PPd", 
]

[exec.sub.paracross]
nodeGroupFrozenCoins=0
#平行链共识停止后主链等待的高度
paraConsensusStopBlocks=30000

[exec.sub.autonomy]
total="13jXcaJB3Sg7oBB2FAZf3VbDB58gHn7PPd"
useBalance=false




[metrics]
#是否使能发送metrics数据的发送
enableMetrics = false
#数据保存模式
dataEmitMode = "influxdb"

[metrics.sub.influxdb]
#以纳秒为单位的发送间隔
database = "logmetrics"
duration = 1000000000
namespace = ""
password = ""
url = "http://influxdb:8086"
username = ""

[pprof]
listenAddr=":8903"

[health]
listenAddr="localhost:8809"
checkInterval=1
unSyncMaxTimes=2
