FixTime = false
Title = "assetchain"
ChainID=10000
version="2.0.0"
CoinSymbol="OCIA"
CoinPrecision=10000
TxHeight = true

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
logConsoleLevel = "info"
loglevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/assetchain.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = true
# 是否打印调用方法
callerFunction = false

[blockchain]
batchsync = false
defCacheSize=512
dbCache = 512
dbPath = "/data/assetchaindatadir"
enableTxQuickIndex = true
isRecordBlockSequence = true
# 升级storedb是否重新执行localdb，主链升级不需要开启，平行链升级需要开启
enableReExecLocal = false
# 使能精简localdb
enableReduceLocaldb = false
enablePushSubscribe = true
singleMode = false
maxFetchBlockNum=128
timeoutSeconds=1
batchBlockNum=128
driver="leveldb"
isStrongConsistency=false
disableShard=true
onChainTimeout=1

[address]
defaultDriver="eth"
[address.enableHeight]
eth=0

[mempool]
poolCacheSize=102400
#minTxFeeRate=0
minTxFeeRate=10
maxTxFeeRate=1000
#disableExecCheck=true
maxTxNumPerAccount = 30000
name="price"
maxTxFee=100000
disableExecCheck = true
isLevelFee=false

[mempool.sub.score]
poolCacheSize=102400
minTxFee=10
maxTxNumPerAccount=30000
timeParam=1      #时间占价格比例
priceConstant=1544  #手续费相对于时间的一个合适的常量,取当前unxi时间戳前四位数,排序时手续费高1e-5~=快1s
pricePower=1     #常量比例

[mempool.sub.price]
poolCacheSize=102400

[p2p]
enable=true
dbCache = 4
driver="leveldb"
dbPath = "/data/assetchaindatadir/addrbook"
grpcLogFile = "grpc33.log"
types = ["dht"]
#waitPid 等待seed导入
waitPid = false

[p2p.sub.gossip]
innerBounds = 300
innerSeedEnable = false
isSeed = false
port = 13802
seeds = []
useGithub = false
msgCacheSize=10240
serverStart=true

[p2p.sub.dht]
#可以自定义设置连接节点
channel = 10003
port = 13801

seeds = ["/ip4/218.75.123.183/tcp/13801/p2p/16Uiu2HAm9fKBw3nYhJpSdBRoQ8YM1Z6UaLxRuFxu8sAUATmLA2JT"] # TODO
#seeds = ["/ip4/10.89.3.10/tcp/13801/p2p/16Uiu2HAm9fKBw3nYhJpSdBRoQ8YM1Z6UaLxRuFxu8sAUATmLA2JT"]

#限定连接数
#暂时限定较小的连接数
maxConnectNum = 50
#区块轻广播最低区块大小，1k
minLtBlockSize = 1
# 是否配置为全节点模式，全节点保存所有分片数据，种子节点应配置为true
isFullNode = true
#设为1为屏蔽默认设置5
maxBroadcastPeers = 1

[p2p.sub.dht.pubsub]
gossipSubD = 10
gossipSubDhi = 20
gossipSubDlo = 7
gossipSubHeartbeatInterval = 900
gossipSubHistoryGossip = 2
gossipSubHistoryLength = 7


[rpc]
certFile = "cert.pem"
enableTLS = false
grpcBindAddr = "localhost:8802"
grpcFuncWhitelist = ["*"]
jrpcBindAddr = "localhost:8801"
jrpcFuncWhitelist = ["*"]
keyFile = "key.pem"
whitelist = ["127.0.0.1"]

[consensus]
name="pos33"
minerstart=true
genesisBlockTime=1652356636
genesis="13Fky3sREhmVeM3Hk5rCbAsh9id9qgwtLv"
minerExecs=["pos33"]

[consensus.sub.pos33]
bootPeers = ["/ip4/218.75.123.183/tcp/10901/p2p/16Uiu2HAmDu5ubvVncWYQ9C9ih5SK5WHVtULzmqSs9ZZqxdM1DQ6p"] # TODO
#bootPeers = ["/ip4/10.89.3.10/tcp/10901/p2p/16Uiu2HAmDu5ubvVncWYQ9C9ih5SK5WHVtULzmqSs9ZZqxdM1DQ6p"]
issueTotal = 202005201314
listenPort = 10901
onlyVoter = false
genesisBlockTime=1652356636
checkFutureBlockHeight=1500000

[[consensus.sub.pos33.genesis]]
minerAddr="14XDiBdV7u73TDzbNYmf3Pihnnsm9qhEiG"
returnAddr="13Fky3sREhmVeM3Hk5rCbAsh9id9qgwtLv"
blsAddr="1HD3KyzUqMKT3fnKCXsFx91PZ1R2tiegXk" # TODO gen from consensus.genesis.minerAddr.privkey
count=1000

[mver.consensus]
fundKeyAddr="14wDnMse45jomBWx1AuHB6KDhVz662YJMx" # TODO more address or same the other
addWalletTx = false
powLimitBits="0x1f00ffff"
maxTxNumber=10000

[mver.consensus.pos33]
ticketPrice1=10000
ticketPrice2=100000
minerFeePersent=10 
rewardTransfer=1
blockReward=15
voteRewardPersent=25
mineRewardPersent=11

[store]
dbCache = 512
dbPath = "/data/assetchaindatadir/kvmvcc"
name="kvmvcc"
driver="leveldb"

[store.sub.kvmvcc]
enableMVCC = false
enableMavlPrefix = false


[store.sub.mavl]
enableMVCC = false
enableMavlPrefix = true
enableMavlPrune = true
enableMemTree = true
enableMemVal = true
pruneHeight = 10000
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen = 200000

[store.sub.kvmvccmavl]
enableMVCC = false
enableMVCCIter = true
enableMVCCPrune = false
enableMavlPrefix = true
enableMavlPrune = true
enableMemTree = true
enableMemVal = true
pruneMVCCHeight = 10000
pruneMavlHeight = 10000
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen = 200000

[crypto]
enableTypes = ["secp256k1", "none", "bls"]

[wallet]
dbCache = 16
dbPath = "/data/assetchainwallet"
minFee=10
driver="leveldb"
signType="secp256k1"

[fork.system]
ForkChainParamV1=0
ForkCheckTxDup=0
ForkBlockHash=0
ForkMinerTime=0
ForkTransferExec=0
ForkExecKey=0
ForkTxGroup=0
ForkResetTx0=0
ForkWithdraw=0
ForkExecRollback=0
ForkCheckBlockTime=0
ForkTxHeight=0
ForkTxGroupPara=0
ForkChainParamV2=0
ForkMultiSignAddress=0
ForkStateDBSet=0
ForkLocalDBAccess=0
ForkBlockCheck=0
ForkBase58AddressCheck=0
#平行链上使能平行链执行器如user.p.x.coins执行器的注册，缺省为0，对已有的平行链需要设置一个fork高度
ForkEnableParaRegExec=0
ForkCacheDriver=0
ForkTicketFundAddrV1=-1 #fork6.3
#主链和平行链都使用同一个fork高度
ForkRootHash=0 

[fork.sub.coins]
Enable=0

[fork.sub.pos33]
Enable=0
ForkReward15=0 
ForkFixReward=0
UseEntrust=0

[fork.sub.ticket]
Enable=0
ForkTicketId = 0 
ForkTicketVrf = 0

[fork.sub.retrieve]
Enable=0
ForkRetrive=0
ForkRetriveAsset=0

[fork.sub.hashlock]
Enable=0
ForkBadRepeatSecret=0

[fork.sub.manage]
Enable=0
ForkManageExec=0
ForkManageAutonomyEnable=-1

[fork.sub.token]
Enable=0
ForkTokenBlackList=0
ForkBadTokenSymbol=0
ForkTokenPrice=300000
ForkTokenSymbolWithNumber=0
ForkTokenCheck=0

[fork.sub.trade]
Enable=0
ForkTradeBuyLimit=0
ForkTradeAsset=0
ForkTradeID=0
ForkTradeFixAssetDB=0
ForkTradePrice=0


[fork.sub.paracross]
Enable=0
ForkParacrossWithdrawFromParachain=0
ForkParacrossCommitTx=0
ForkLoopCheckCommitTxDone=0
#fork for 6.4
ForkParaAssetTransferRbk=0
ForkParaSelfConsStages=0
#仅平行链适用
ForkParaFullMinerHeight=-1
ForkParaRootHash=0
ForkParaSupervision=0
ForkParaAutonomySuperGroup=-1
ForkParaFreeRegister = 0

[fork.sub.multisig]
Enable=0

[fork.sub.autonomy]
Enable=0
ForkAutonomyDelRule=0
ForkAutonomyEnableItem=0

[fork.sub.unfreeze]
Enable=0
ForkTerminatePart=0
ForkUnfreezeIDX=0

[fork.sub.store-kvmvccmavl]
ForkKvmvccmavl=0

[fork.sub.evm]
Enable=0
ForkEVMState=0
ForkEVMABI=0
ForkEVMFrozen=0
ForkEVMKVHash=0
ForkEVMYoloV1=0
ForkEVMTxGroup=0

[fork.sub.evmxgo]
Enable=0

[exec]
enableMVCC = false
enableStat = false
disableAddrIndex = false
disableFeeIndex = false
disableTxIndex = false


[exec.sub.coins]
disableAddrReceiver = true
disableCheckTxAmount = true


[exec.sub.token]
#配置一个空值，防止配置文件被覆盖
tokenApprs=["165miLmdAg9rE3q2NWNZQPcaJmnMTCWu4k"]
saveTokenTxList = false

[exec.sub.relay]
genesis="19sVCTBpeLzjT7JzRRZLqqDDpyKvZ83dfm"

[exec.sub.manage]
superManager=[
    "1G6Mev49HmAbvd7tPA23aGHKcr59nBXZfD", 
    "1348VpJs2mHby2q8WL78y8TgQwvYUB7Boq", 
    "1NBkw3urHYVuKjUzTpYdj7ueYmXXoW7LR4",
]

[exec.sub.paracross]
nodeGroupFrozenCoins=0
#平行链共识停止后主链等待的高度
paraConsensusStopBlocks=30000

[exec.sub.autonomy]
total="1pEXnweTTdjqPRv4LTV9pB25qneK9hEYS"
useBalance=false

[mver.autonomy]
#最小委员会数量
minBoards=20
#最大委员会数量
maxBoards=40
#公示一周时间，以区块高度计算
publicPeriod=120960
#单张票价
ticketPrice=3000
#重大项目公示金额阈值
largeProjectAmount=1000000
#创建者消耗金额bty
proposalAmount=500
#董事会成员赞成率，以%计，可修改
boardApproveRatio=51
#全体持票人参与率，以%计
pubAttendRatio=51
#全体持票人赞成率，以%计
pubApproveRatio=51
#全体持票人否决率，以%计
pubOpposeRatio=33
#提案开始结束最小周期高度
startEndBlockPeriod=720
#提案高度 结束高度最大周期 100W
propEndBlockPeriod=1000000
#最小董事会赞成率
minBoardApproveRatio=50
#最大董事会赞成率
maxBoardApproveRatio=66
#最小全体持票人否决率
minPubOpposeRatio=33
#最大全体持票人否决率
maxPubOpposeRatio=50
#可以调整，但是可能需要进行范围的限制：参与率最低设置为 50%， 最高设置为 80%，赞成率，最低 50.1%，最高80%
#不能设置太低和太高，太低就容易作弊，太高则有可能很难达到
#最小全体持票人参与率
minPubAttendRatio=50
#最大全体持票人参与率
maxPubAttendRatio=80
#最小全体持票人赞成率
minPubApproveRatio=50
#最大全体持票人赞成率
maxPubApproveRatio=80
#最小公示周期
minPublicPeriod=120960
#最大公示周期
maxPublicPeriod=241920
#最小重大项目阈值(coin)
minLargeProjectAmount=1000000
#最大重大项目阈值(coin)
maxLargeProjectAmount=3000000
#最小提案金(coin)
minProposalAmount=20
#最大提案金(coin)
maxProposalAmount=2000
#每个时期董事会审批最大额度300万
maxBoardPeriodAmount =3000000
#时期为一个月
boardPeriod=518400
#4w高度，大概2天 (未生效)
itemWaitBlockNumber=40000


[metrics]
#是否使能发送metrics数据的发送
enableMetrics = false
#数据保存模式
dataEmitMode = "influxdb"

[metrics.sub.influxdb]
#以纳秒为单位的发送间隔
database = "logmetrics"
duration = 1000000000
namespace = ""
password = ""
url = "http://influxdb:8086"
username = ""

[pprof]
listenAddr=":8903"

[health]
listenAddr="localhost:8809"
checkInterval=1
unSyncMaxTimes=2
