FixTime = false
Title = "ycc-test12"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
logConsoleLevel = "error"
loglevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = true
# 是否打印调用方法
callerFunction = false

[blockchain]
batchsync = false
dbCache = 64
dbPath = "datadir"
enableTxQuickIndex = true
isRecordBlockSequence = false
# 升级storedb是否重新执行localdb，bityuan主链升级不需要开启，平行链升级需要开启
enableReExecLocal = false
# 使能精简localdb
enableReduceLocaldb = true
singleMode = false

[p2p]
dbCache = 4
dbPath = "datadir/addrbook"
grpcLogFile = "grpc33.log"
types = ["dht"]
#waitPid 等待seed导入
waitPid = false

[p2p.sub.gossip]
innerBounds = 300
innerSeedEnable = true
isSeed = false
port = 13902
useGithub = false

[p2p.sub.dht]
#可以自定义设置连接节点
channel = 9
port = 13801
seeds = [
  "/ip4/42.159.83.68/tcp/13801/p2p/16Uiu2HAmMQVuCHpNXjayMaiYz2LWGzqp9aCLxHFS8W8m2UKz2yKB",
  "/ip4/40.73.244.123/tcp/13801/p2p/16Uiu2HAmPvU4StUPkuSK9Td7g2xF41BBSdsRaQ6KmuvpnBJebAiw",
  "/ip4/139.217.232.4/tcp/13801/p2p/16Uiu2HAmV2AWeFqq8byHbJUpNGxLyXNtwQRkwADxiEqXRxoGCEn1",
  "/ip4/52.130.198.4/tcp/13801/p2p/16Uiu2HAm9GG1TFCsv54PwGUzdRPTihEu8X7p8EJzBhwNgCm7ktn5",
  "/ip4/52.130.197.108/tcp/13801/p2p/16Uiu2HAmMoKLKB1VBCCn7DTaPqDtg38EfUYBqsE4HWvogD6czjRX",
]
#dht 版本还不稳定，暂时限定较小的连接数
maxConnectNum = 50
#区块轻广播最低区块大小，1k
minLtBlockSize = 1
# 是否配置为全节点模式，全节点保存所有分片数据，种子节点应配置为true
# 全节点可以切换为分片节点，暂不支持分片节点切换为全节点
isFullNode = false
# 兼容老版本广播节点数，目前比特元网络已基本全面升级6.5.3，新版本不再支持广播发送至老版本
# 设为1为屏蔽默认设置5
maxBroadcastPeers = 1

[p2p.sub.dht.pubsub]
gossipSubD = 10
gossipSubDhi = 20
gossipSubDlo = 7
gossipSubHeartbeatInterval = 900
gossipSubHistoryGossip = 2
gossipSubHistoryLength = 7

[rpc]
certFile = "cert.pem"
enableTLS = false
grpcBindAddr = "localhost:9902"
grpcFuncWhitelist = ["*"]
jrpcBindAddr = "localhost:9901"
jrpcFuncWhitelist = ["*"]
keyFile = "key.pem"
whitelist = ["127.0.0.1"]

[consensus.sub.pos33]
bootPeers = [
  "/ip4/42.159.83.68/tcp/10901/p2p/16Uiu2HAmErmNhtS145Lv5fe9FWrHSrNjPkp1eMLeLgi6t3sdr1of",
  "/ip4/52.130.197.108/tcp/10901/p2p/16Uiu2HAkv6Qmr3JoFCNxQF8PHndwkBbm4sKvBRnm4Acx5tx5wScQ",
  "/ip4/52.130.198.4/tcp/10901/p2p/16Uiu2HAkxKD5BZZ7JUdSHqozNb2oVfQBMHx7Lc7w6ZjjDBmiHXq1",
  "/ip4/139.217.232.4/tcp/10901/p2p/16Uiu2HAmDxexHSNZvvgXCe5kV1Qq7E4tQbETb68xww2fBe3HQdLg",
  "/ip4/40.73.244.123/tcp/10901/p2p/16Uiu2HAm1nj2pAWwk7KimhZLYB9GBXf2eCGGbroLyCoQRGv7bsEm",
]
forwardServers = ["124.71.10.240:10902"]
listenPort = 10901
onlyVoter = false

[mempool]
maxTxNumPerAccount = 100

[store]
dbCache = 128
dbPath = "datadir/mavltree"

[store.sub.mavl]
enableMVCC = false
enableMavlPrefix = true
enableMavlPrune = true
enableMemTree = true
enableMemVal = true
pruneHeight = 10000
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen = 200000

[store.sub.kvmvccmavl]
enableMVCC = false
enableMVCCIter = true
enableMVCCPrune = false
enableMavlPrefix = true
enableMavlPrune = true
enableMemTree = true
enableMemVal = true
pruneMVCCHeight = 10000
pruneMavlHeight = 10000
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000,默认200000
tkCloseCacheLen = 200000

[wallet]
dbCache = 16
dbPath = "wallet"

[exec]
enableMVCC = false
enableStat = false

[exec.sub.token]
saveTokenTxList = false

[metrics]
#是否使能发送metrics数据的发送
enableMetrics = false
#数据保存模式
dataEmitMode = "influxdb"

[metrics.sub.influxdb]
#以纳秒为单位的发送间隔
database = "chain33metrics"
duration = 1000000000
namespace = ""
password = ""
url = "http://influxdb:8086"
username = ""
