ChainID = 999
CoinPrecision = 100000000
CoinSymbol = "ycc"
Title = "pos33"
version = "1.0.0.1"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
logConsoleLevel = "error"
loglevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"

[blockchain]
# 区块数据目录
batchsync = false
dbCache = 256
dbPath = "datadir"
# 是否单节点运行
singleMode = false
# 是否关闭区块广播
disableBlockBroadcast = false
enableTxQuickIndex = true
isRecordBlockSequence = false
# 升级storedb是否重新执行localdb，bityuan主链升级不需要开启，平行链升级需要开启
enableReExecLocal = false
# 使能精简localdb
disableShard = true
enablePushSubscribe = true
enableReduceLocaldb = true
isParaChain = false

[p2p]
dbPath = "datadir/addrbook"
grpcLogFile = "grpc33.log"

[p2p.sub.dht]
# 分组通道, 同一个网络的channel必须相同
channel = 9
# p2p服务端口
port = 13801
#可以自定义设置连接节点
seeds = [
  "/ip4/121.52.224.84/tcp/13801/p2p/16Uiu2HAm4KV8puoy5SKLXhz36E1vkrnMTsU5NBy98qoyBhrfnKoj",
]

[rpc]
certFile = "cert.pem"
enableTLS = false
grpcBindAddr = "localhost:9902"
grpcFuncWhitelist = ["*"]
jrpcBindAddr = "localhost:9901"
jrpcFuncWhitelist = ["*"]
keyFile = "key.pem"
whitelist = ["127.0.0.1"]

[consensus.sub.pos33]
bootPeers = [
  "/ip4/121.52.224.84/tcp/10801/p2p/16Uiu2HAmErmNhtS145Lv5fe9FWrHSrNjPkp1eMLeLgi6t3sdr1of",
]
issueTotal = 10000000000
listenPort = 10801

[store]
dbPath = "datadir/kvmvcc"

[wallet]
coinType = "ycc"
dbPath = "wallet"

[health]
listenAddr = "localhost:8708"
